"""añade imagen al modelo post

Revision ID: 8743bf11ce49
Revises: 2bf8ce8c32c9
Create Date: 2023-10-11 16:27:52.523400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8743bf11ce49'
down_revision = '2bf8ce8c32c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
